services:
  pg-dialog-service:
    image: postgres:16.1-alpine3.18
    container_name: pg-dialog-service
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGPASSWORD: pass
      TZ: Europe/Moscow
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./pg_data/master/:/var/lib/postgresql/data
    networks:
      shared-net:
        aliases:
          - pg-dialog-service.shared
    hostname: pg-dialog-service
    env_file: ".env"
  redis:
    image: redis:7.2.4
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
      - ./load_test/dialog_functions.lua:/dialog_functions.lua
    command:
      - '--appendonly'
      - 'yes'
      - '--save'
      - '60 10'
    environment:
      - REDIS_PASSWORD=123123vv
      - REDIS_LRU_LIMIT_MB=1024
  ms-dialog:
    container_name: ms-dialog
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    networks:
      shared-net:
    depends_on:
      - pg-dialog-service
    env_file:
      - .env

networks:
  shared-net:
    external: true
    name: shared-app-network
