CREATE TABLE dialog (
    id SERIAL PRIMARY KEY,
    user_id_sender INTEGER,
	  user_id_recipient INTEGER,
	  msg TEXT,
    state BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE auth (
    id SERIAL PRIMARY KEY,
    user_id INTEGER,
	  token VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
